export enum COMMANDS {
	SAY = 0,
	NRP = 1,
	DO = 2,
	TRY = 3,
	TODO = 4,
	SCREAM = 5,
	WHISPER = 6,
	FACTION = 7,
	FACTION_NRP = 8,
	ORG = 9,
	ORG_NRP = 10,
	NEWS = 11,
	DEPARTMENT = 12,
	MEGAFON = 13
}

export const commandsList = {
	say: COMMANDS.SAY,
	b: COMMANDS.NRP,
	do: COMMANDS.DO,
	try: COMMANDS.TRY,
	todo: COMMANDS.TODO,
	s: COMMANDS.SCREAM,
	w: COMMANDS.WHISPER,
	fb: COMMANDS.FACTION_NRP,
	rb: COMMANDS.FACTION_NRP,
	famb: COMMANDS.ORG_NRP,
	ffb: COMMANDS.ORG_NRP,
	fam: COMMANDS.ORG,
	ff: COMMANDS.ORG,
	f: COMMANDS.FACTION,
	r: COMMANDS.FACTION,
	news: COMMANDS.NEWS,
	d: COMMANDS.DEPARTMENT,
	m: COMMANDS.MEGAFON
};
