export const items: { [key: string]: string[] } = {
	repair: ['Complet'],
	engine: ['default', 'STAGE 1', 'STAGE 2', 'STAGE 3', 'STAGE 4'],
	transmission: ['default', 'Stradala', 'Sport', 'Curse'],
	brakes: ['default', 'Stradale', 'Sport', 'Curse'],
	turbo: ['default', 'Kit Turbo'],
	suspension: ['default', 'Coborata', 'Stradala', 'Sport', 'Curse'],	
	armor: ['default', '20%', '40%', '60%', '80%', '100%'],
	engine_sound: [
		'6.0L V8',
		'3.0L I6',
		'5.2L V10',
		'2.6L I6',
		'1.3L Twin-Rotor',
		'5.8L Twin-Charged V8',
		'7.3L V12',
		'6.0L V12',
		'2.0L I4',
		'4.0L Flat-6',
		'5.2L V8'
	],
	horn: [
		'default',
		'Camion',
		'Politie',
		'Clovn',
		'Muzical 1',
		'Muzical 2',
		'Muzical 3',
		'Muzical 4',
		'Muzical 5',
		'Trompeta trista',
		'Clasic 1',
		'Clasic 2',
		'Clasic 3',
		'Clasic 4',
		'Clasic 5',
		'Clasic 6',
		'Clasic 7',
		'Nota - Do',
		'Nota - Re',
		'Nota - Mi',
		'Nota - Fa',
		'Nota - Sol',
		'Nota - La',
		'Nota - Si',
		'Nota - Do (inalt)',
		'Jazz 1',
		'Jazz 2',
		'Jazz 3',
		'Jazz (repetare)'
	],
	tint: ['default', 'Negru pur', 'Fumuriu inchis', 'Fumuriu deschis', 'Limo', 'Verde'],
	lights: [
		'default',
		'Alb',
		'Albastru',
		'Albastru deschis',
		'Verde',
		'Verde deschis',
		'Galben deschis',
		'Galben',
		'Portocaliu',
		'Rosu',
		'Roz',
		'Violet',
		'Violet deschis'
	],
	neon: ['default', 'Instaleaza'],
	plate: [
		'default',
		'Galben pe negru',
		'Galben pe albastru',
		'Albastru pe alb #2',
		'Albastru pe alb #3',
		'Negru pe alb'
	],
	paint: ['Culoare principala', 'Culoare secundara', 'Culoare jante', 'Fum anvelope'],	
	rims: [],
	spoiler: [],
	sideskirt: [],
	exhaust: [],
	hood: [],
	roof: [],
	frame: [],
	grille: [],
	livery: [],
	front_bumper: [],
	rear_bumper: []
};
